### ISSUE TITLE
C3D_SetScissor parameter names

### ISSUE THREAD

**Issue by usagirei** [fincs/citro3d#11]
At the time of  posting this issue, on [C3D_SetScissor](https://github.com/fincs/citro3d/blob/b276d8cec2fa77d6b6082fa5e5570e19307ebcaf/source/base.c#L129), the method signature parameters are: `left,top,right,bottom`
I suggest that they should probably be named `left,bottom,right,top` instead.
Or maybe `x0,y0,x1,y1`

Considering the Framebuffer Rotated 90 Degrees Clockwise, calling:

``` c
C3D_SetScissor(GPU_SCISSORMODE::GPU_SCISSOR_NORMAL, 20, 40, 80, 160);
```

Will result in the following clip region being used to render (Black Area):
![image](http://i.imgur.com/5KkNKB4.png)

`left:20, top:40, right:80, bottom:160` thus makes no sense, as _top_ is below _bottom_.

**Comment by yuriks** [comment]
I think your diagram is incorrect: the PICA "has" (by convention) the origin on the top-left, with x and y increasing to the right and to the bottom, respectively, this is opposite to the OpenGL convention. With that in view, the names make sense.

However, I *really* recommend `x0,y0,x1,y1` or `x_min,y_min,x_max,y_max` instead of any format involving the names of each side, because that completely removes any confusion about coordinate frames.

**Comment by usagirei** [comment]
Not really sure about where origin is for scissor testing, but from what i tested when to create that image, 0,0 is in bottom right of 3ds Screen (bottom left if you tilt the 3ds 90 CW)
but using x,y instead of top left or w/e makes it less confusing as to what is where

**Comment by yuriks** [comment]
You're probably V-flipping while doing a display transfer. The origin of the LCD framebuffer is the top-left (with the 3DS 90° CW).

**Comment by usagirei** [comment]
No v-flip as far as i'm aware, my display transfer flags are:
```cpp
#define DISPLAY_TRANSFER_FLAGS \
	(GX_TRANSFER_FLIP_VERT(0) | GX_TRANSFER_OUT_TILED(0) | GX_TRANSFER_RAW_COPY(0) | \
	GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8) | GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8) | \
	GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_NO))
```

and i'm using 
```cpp
C3D_RenderTargetSetOutput(_topLeftRt, GFX_TOP, GFX_LEFT, DISPLAY_TRANSFER_FLAGS);
```
with it
