### ISSUE TITLE
TexEnv data is not always updated after modification

### ISSUE THREAD

**Issue by Steveice10** [fincs/citro3d#3]
Currently, a TexEnv is flagged for update in C3D_GetTexEnv, rather than C3D_TexEnvSrc, etc. As a result, if one retrieves a TexEnv with C3D_GetTexEnv and modifies it after drawing something, which triggers updates and clears flags, the final state will not take effect until after the next C3D_GetTexEnv call.

**Comment by fincs** [comment]
This is by design. Several state structures in citro3d like C3D_TexEnv are supposed to be independent of the current GPU state. The current design allows users to make their own C3D_TexEnv structures separate from the ones that are internally managed in the GPU context and configure them - to upload them the user can use C3D_SetTexEnv. Adding the dirty flag to any of the functions that configure a TexEnv structure would not make sense. Moreover, the return value of C3D_GetTexEnv is not supposed to be stored in a persistent variable - every time you want to modify the state of a TexEnv stage directly, you are supposed to call C3D_GetTexEnv and call the appropriate functions using its return value right away.

**Comment by Steveice10** [comment]
I can understand that, I just felt it a bit confusing as a beginner to this library, that modifying the TexEnv again did nothing.

With that in mind, I feel like it would make more sense to require SetTexEnv than flagging it dirty in GetTexEnv, as it may not have actually changed and could cause the confusion I had.
